#!/usr/bin/env python3
"""Validate the rule registry and generate its human-readable source matrix."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "skills/frame-business-research-problem/references/rule-registry.yaml"
MANIFEST = ROOT / "literature/manifest.yaml"
TARGET = ROOT / "skills/frame-business-research-problem/references/source-to-rule-matrix.md"
ANTI_PATTERNS = ROOT / "skills/frame-business-research-problem/references/anti-patterns.md"
REQUIRED = {
    "rule_id", "imperative_text", "rationale", "layer", "applicable_domains",
    "applicable_modes", "supporting_source_ids", "source_tiers", "status",
    "counterconditions", "limitations", "associated_anti_patterns",
    "affected_evaluation_criteria", "version_introduced",
}
STATUSES = {
    "core_triangulated", "official_outlet_guidance", "domain_specific",
    "provisional_single_source", "exemplar_observation", "rejected_or_not_generalizable",
    "original_framework_rule",
}


def load_yaml(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a mapping")
    return value


def validate(registry: dict[str, Any], manifest: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    anti_pattern_ids = set(re.findall(r"^\| (AP-[0-9]+) \|", ANTI_PATTERNS.read_text(encoding="utf-8"), re.MULTILINE))
    sources = {item["source_id"]: item for item in manifest.get("sources", [])}
    seen: set[str] = set()
    for index, rule in enumerate(registry.get("rules", [])):
        path = f"rules[{index}]"
        missing = REQUIRED - set(rule)
        if missing:
            errors.append(f"{path}: missing {sorted(missing)}")
            continue
        if rule["rule_id"] in seen:
            errors.append(f"{path}: duplicate rule_id {rule['rule_id']}")
        seen.add(rule["rule_id"])
        if rule["status"] not in STATUSES:
            errors.append(f"{path}: invalid status {rule['status']}")
        support = rule["supporting_source_ids"]
        unknown = sorted(set(support) - set(sources))
        if unknown:
            errors.append(f"{path}: unknown source IDs {unknown}")
            continue
        actual_tiers = sorted({sources[item]["source_tier"] for item in support})
        if sorted(rule["source_tiers"]) != actual_tiers:
            errors.append(f"{path}: source_tiers do not match manifest support")
        for field in ("counterconditions", "limitations", "associated_anti_patterns", "affected_evaluation_criteria"):
            if not isinstance(rule[field], list) or not rule[field]:
                errors.append(f"{path}.{field}: must be nonempty")
        unknown_anti_patterns = sorted(set(rule["associated_anti_patterns"]) - anti_pattern_ids)
        if unknown_anti_patterns:
            errors.append(f"{path}: unknown anti-pattern IDs {unknown_anti_patterns}")
        if rule["status"] == "core_triangulated":
            authoritative = [sources[item] for item in support if sources[item]["source_tier"] != "tier_c_exemplar_execution"]
            author_sets = {tuple(item["authors"]) for item in authoritative}
            tiers = {item["source_tier"] for item in authoritative}
            qualifies = len(author_sets) >= 2 or {
                "tier_a_official_guidance_or_editorial", "tier_b_peer_reviewed_foundational"
            } <= tiers
            if len(authoritative) < 2 or not qualifies:
                errors.append(f"{path}: core_triangulated support is not independent/tier-qualified")
    if not registry.get("rules"):
        errors.append("rules: must be nonempty")
    for source_id, source in sources.items():
        expected = sorted(
            rule["rule_id"] for rule in registry.get("rules", [])
            if source_id in rule.get("supporting_source_ids", [])
        )
        if sorted(source.get("supported_rule_ids", [])) != expected:
            errors.append(f"manifest source {source_id}: supported_rule_ids do not match registry")
    return errors


def render(registry: dict[str, Any], manifest: dict[str, Any]) -> str:
    sources = {item["source_id"]: item for item in manifest["sources"]}
    lines = [
        "# Source-to-Rule Matrix", "",
        "<!-- Generated by tools/generate_rule_matrix.py. Do not edit manually. -->", "",
        "The rule registry is canonical. Source support is bounded by each audited card's recorded access scope.", "",
        "| Rule | Status | Layer | Imperative | Supporting sources | Counterconditions |", "|---|---|---|---|---|---|",
    ]
    for rule in registry["rules"]:
        support = "; ".join(
            f"`{item}` ({sources[item]['source_tier']})" for item in rule["supporting_source_ids"]
        )
        counter = " ".join(rule["counterconditions"])
        lines.append(
            f"| `{rule['rule_id']}` | `{rule['status']}` | `{rule['layer']}` | {rule['imperative_text']} | {support} | {counter} |"
        )
    lines.extend(["", "## Coverage", ""])
    for source_id in sources:
        rules = [rule["rule_id"] for rule in registry["rules"] if source_id in rule["supporting_source_ids"]]
        lines.append(f"- `{source_id}`: {', '.join(f'`{item}`' for item in rules) if rules else 'no admitted rule; retained for bounded synthesis'}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry, manifest = load_yaml(REGISTRY), load_yaml(MANIFEST)
    errors = validate(registry, manifest)
    if errors:
        print("Rule registry validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    expected = render(registry, manifest)
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print(f"Generated matrix is stale: {TARGET}")
            return 1
        print("Generated rule matrix is current.")
        return 0
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
