#!/usr/bin/env python3
"""Generate the public rubric reference from the canonical JSON policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "evals" / "rubrics" / "business-framing-v2.json"
TARGET = ROOT / "skills" / "frame-business-research-problem" / "references" / "evaluation-rubric.md"


def load_policy() -> dict[str, Any]:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def render(policy: dict[str, Any]) -> str:
    lines = [
        "# Evaluation Rubric",
        "",
        "<!-- Generated by tools/generate_rubric.py from evals/rubrics/business-framing-v2.json. Do not edit manually. -->",
        "",
        f"Canonical rubric version: `{policy['version']}`.",
        "",
        "Score only what is visible in the artifact. Do not award intent. First assess fidelity eligibility, then score each applicable layer independently.",
        "",
        "## 100-point rubric",
        "",
        "| Layer | Points | Minimum | Applies | Full-credit standard |",
        "|---|---:|---:|---|---|",
    ]
    for category in policy["categories"]:
        applies = category["applicability"].replace("_", " ")
        lines.append(
            f"| {category['label']} | {category['weight']} | {category['minimum']} | {applies} | {category['anchors']['full']} |"
        )
    lines.extend([
        "",
        "For each applicable layer, record an integer score and an artifact-specific reason. Preserve the uncapped `raw_total` from 0 to 100. Mark a conditional layer not applicable only when the output neither requests nor claims that layer; do not silently award its minimum.",
        "",
        "## Success policy",
        "",
        f"Overall success requires all of the following: a capped total of at least {policy['passing_score']}; every applicable layer at or above its minimum; and no fidelity hard failure. A high score in prose or later layers cannot compensate for a failed fidelity gate.",
        "",
        "## Hard failures",
        "",
    ])
    for failure in policy["hard_failures"]:
        lines.append(f"- `{failure['id']}` ({failure['gate']}): {failure['description']}")
    lines.extend([
        "",
        f"Preserve the raw score when a hard failure occurs. Set `capped_total = min(raw_total, {policy['hard_failure_cap']})`. Any fidelity-gate hard failure is an automatic failure, regardless of the capped total.",
        "",
        "## Scoring procedure",
        "",
        "1. Read the supplied research specification and decision-time facts before the response.",
        "2. Mark actor, timing, information, behavior, constraints, and objective as pass, fail, unknown, or not assessed.",
        "3. If information is insufficient, preserve `unknown` or `not_assessed`; do not infer a pass.",
        "4. Detect and report hard failures separately from point deductions.",
        "5. Score every applicable layer and apply its minimum.",
        "6. Calculate the raw total, apply the hard-failure cap, and then determine success.",
        "7. Report the primary remaining weakness and the smallest information or revision needed to address it.",
        "",
        "For blind comparisons, remove condition labels and randomize output order. Report paired and category deltas, pass and hard-failure rates, refusal behavior, regressions, verbosity, ceiling effects, structural preference bias, mean absolute judge differences, total-score correlation, and hard-failure agreement. Disclose judge model, prompt, run date, same-model judging, and residual contamination risk.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if the committed Markdown differs from generated output")
    args = parser.parse_args()
    expected = render(load_policy())
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print(f"Generated rubric is stale: {TARGET}")
            return 1
        print("Generated rubric is current.")
        return 0
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
